"""empty message

Revision ID: 3123de8a938b
Revises: 66a6dad707b6
Create Date: 2025-05-01 16:37:27.859647

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3123de8a938b"
down_revision: Union[str, None] = "66a6dad707b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "car", sa.Column("number_of_seats", sa.Integer(), nullable=True)
    )
    op.add_column(
        "car", sa.Column("trunk_volume", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("car", "trunk_volume")
    op.drop_column("car", "number_of_seats")
    # ### end Alembic commands ###
