"""empty message

Revision ID: 66a6dad707b6
Revises: 0f7e9f8f9da7
Create Date: 2025-05-01 14:19:11.697050

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "66a6dad707b6"
down_revision: Union[str, None] = "0f7e9f8f9da7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rental_class",
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "car", sa.Column("rental_class_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(
        None, "car", "rental_class", ["rental_class_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "car", type_="foreignkey")
    op.drop_column("car", "rental_class_id")
    op.drop_table("rental_class")
    # ### end Alembic commands ###
