"""empty message

Revision ID: a2ca900693ff
Revises: 6f0361d4730f
Create Date: 2025-05-01 22:48:26.643932

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a2ca900693ff"
down_revision: Union[str, None] = "6f0361d4730f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "car_image_car_id_fkey", "car_image", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "car_image", "car", ["car_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "car_image", type_="foreignkey")
    op.create_foreign_key(
        "car_image_car_id_fkey", "car_image", "car", ["car_id"], ["id"]
    )
    # ### end Alembic commands ###
