"""create car table

Revision ID: f6d12df264c4
Revises: eb838570ef17
Create Date: 2025-04-24 19:22:46.674552

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f6d12df264c4"
down_revision: Union[str, None] = "eb838570ef17"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "car",
        sa.Column("car_brand_id", sa.Integer(), nullable=False),
        sa.Column("model", sa.String(length=32), nullable=False),
        sa.Column("transmission_id", sa.Integer(), nullable=False),
        sa.Column("body_id", sa.Integer(), nullable=False),
        sa.Column("year_of_issue", sa.DateTime(timezone=True), nullable=False),
        sa.Column("engine_type_id", sa.Integer(), nullable=False),
        sa.Column("drive_id", sa.Integer(), nullable=False),
        sa.Column("mileage", sa.Integer(), nullable=False),
        sa.Column("price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["body_id"], ["car_body.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["car_brand_id"], ["car_brand.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["drive_id"], ["drive_type.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["engine_type_id"], ["engine_type.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["transmission_id"], ["transmission.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("car")
    # ### end Alembic commands ###
